<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="generator" content="Uguu {{pkgVersion}}">
		<meta name="Description" content="{{SiteMetaInfo}}">
		<title>{{siteName}} &middot; {% block title %}Kawaii Temporary File Hosting{% endblock %}</title>
		<link rel="icon" href="favicon.ico">
		<link rel="stylesheet" href="uguu.min.css">
		<script src="uguu.min.js"></script>
	</head>
	<body>
		<div class="container">
			{% block body %}What the fuck are you doing here, <span lang="jp">baka</span>?{% endblock %}
		</div>
	</body>
</html>
